### ISSUE TITLE
Table is not sortable

### ISSUE THREAD

**Issue by micheledallatorre** [p101s2/p101s2.github.io#1]
Hello,
is the table supposed to be sortable?
Clicking on the header columns, e.g. "company", does not change anything...

```
main.js:117 Uncaught ReferenceError: sortKey is not defined
at toggleSort (main.js:117)
    at HTMLTableCellElement.onclick ((index):54)
```

Thanks for the good work! :+1:

**Comment by inyounghong** [comment]
Hello,
Thanks for the catch! The columns are sortable now.

**Comment by micheledallatorre** [comment]
Great, well done! :+1:
